INSERT INTO webforum_database.posts VALUES (1, '1 First Post', NULL);
INSERT INTO webforum_database.posts VALUES (2, '2 Second Post', NULL);
INSERT INTO webforum_database.posts VALUES (3, '2 1 First Reply to Second Post', 2);
INSERT INTO webforum_database.posts VALUES (4, '2 1 1 First Reply to First Reply to Second Post', 3);
INSERT INTO webforum_database.posts VALUES (5, '2 1 2 Second Reply to First Reply to Second Post', 4);
INSERT INTO webforum_database.posts VALUES (6, '2 2 Second Reply to Second Post', 2);
INSERT INTO webforum_database.posts VALUES (7, '1 1 First Reply to First Post', 1);
INSERT INTO webforum_database.posts VALUES (8, '1 2 Second Reply to First Post', 1);
INSERT INTO webforum_database.posts VALUES (9, '1 3 Third Reply to First Post', 1);
INSERT INTO webforum_database.posts VALUES (10, '1 2 1 First Reply to Second Reply to First Post', 8);
INSERT INTO webforum_database.posts VALUES (11, '1 3 1 First Reply to Third Reply to First Post', 9);
INSERT INTO webforum_database.posts VALUES (12, '1 3 1 1 First Reply to First Reply to Third Reply to First Post', 11);
INSERT INTO webforum_database.posts VALUES (13, '1 3 1 2 Second Reply to First Reply to Third Reply to First Post', 11);
